# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Bygg React app
          command: |
            npm ci && npm run build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Tester
          command: |
            npm run test
      - persist_to_workspace:
          root: ./
          paths:
            - build/*

  build-docker-image:
    docker:
      - image: circleci/node:11.7.0
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: build/
      - run:
          name: Bygger Docker image
          command: docker build -t "$DOCKER_IMAGE_VERSIONED" .
      - run:
          name: Pusher Docker image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push "$DOCKER_IMAGE_VERSIONED"

  deploy-til-dev:
    docker:
      - image: circleci/node:11.7.0
    steps:
      - sett-miljovariabler
      - build-docker-image
      - run:
          name: Deployer til dev
          command: |
            curl -i \
                -X POST \
                -d '{
                     "ref": "'"$COMMIT_SHORT"'",
                     "description": "Automated deployment request for personopplysninger from team personbruker",
                     "environment": "dev-sbs",
                     "required_contexts": [],
                     "payload": {
                       "version": [1, 0, 0],
                       "team": "personbruker",
                       "kubernetes": {
                         "resources": ['"$(cat nais-dev.json | jq '.spec.image = "'$DOCKER_IMAGE_VERSIONED'"')"']
                       }
                     }
                   }' \
                -H "Accept: application/vnd.github.ant-man-preview+json" \
                -u "$GH_USER":"$GH_TK" \
                https://api.github.com/repos/navikt/personopplysninger/deployments

  deploy-til-prod:
    docker:
      - image: circleci/node:11.7.0
    steps:
      - sett-miljovariabler
      - run:
          name: Deployer til prod
          command: |
            curl -i \
                -X POST \
                -d '{
                     "ref": "'"$COMMIT_SHORT"'",
                     "description": "Automated deployment request for personopplysninger from team personbruker",
                     "environment": "prod-sbs",
                     "required_contexts": [],
                     "payload": {
                       "version": [1, 0, 0],
                       "team": "personbruker",
                       "kubernetes": {
                         "resources": ['"$(cat nais-prod.json | jq '.spec.image = "'$DOCKER_IMAGE_VERSIONED'"')"']
                       }
                     }
                   }' \
                -H "Accept: application/vnd.github.ant-man-preview+json" \
                -u "$GH_USER":"$GH_TK" \
                https://api.github.com/repos/navikt/personopplysninger/deployments

commands:
  sett-miljovariabler:
    steps:
      - run:
          name: Setter miljÃ¸variable
          command: |
            echo 'export COMMIT_SHORT="$(git rev-parse --short HEAD)"' >> $BASH_ENV
            echo 'export RELEASE_VERSION="$(git rev-list --count $CIRCLE_SHA1)"' >> $BASH_ENV
            echo 'export BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD)"' >> $BASH_ENV
            echo 'export BRANCH_PREFIX=`[ $BRANCH_NAME == "master" ] && echo "" || echo $BRANCH_NAME\_`' >> $BASH_ENV
            echo 'export DOCKER_IMAGE_VERSIONED="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$BRANCH_PREFIX$RELEASE_VERSION"' >> $BASH_ENV

workflows:
  bygg-og-deploy:
    jobs:
      - build-react-app
      - bekreft-deploy-til-dev:
          type: approval
          requires:
            - build-react-app
          filters:
            branches:
              ignore:
                - master
      - deploy-til-dev:
          requires:
            - build-react-app
          filters:
            branches:
              only:
                - master
      - deploy-til-dev:
          requires:
            - bekreft-deploy-til-dev
      - bekreft-deploy-til-prod:
          type: approval
          requires:
            - deploy-til-dev
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
      - deploy-til-prod:
          requires:
            - bekreft-deploy-til-prod
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
